# Generated by Django 5.1.3 on 2024-11-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=11, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('code', models.SmallIntegerField()),
                ('expire', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
