# Generated by Django 5.1.3 on 2024-11-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expire',
            field=models.DateTimeField(),
        ),
    ]
