# Generated by Django 5.1.3 on 2025-05-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_myinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
