# Generated by Django 5.1.3 on 2024-11-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='min_weight',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductAttributes',
        ),
    ]
