# Generated by Django 5.1.3 on 2024-11-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_country_product_min_weight_product_quality_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',)},
        ),
    ]
