# Generated by Django 5.1.3 on 2024-11-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
