# Generated by Django 5.1.3 on 2024-11-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
    ]
